language: c
addons:
  apt:
    packages:
      - libx11-dev
      - libxinerama-dev
script:
  - make PREFIX=/tmp/usr/local PREFIXSHARE=/tmp/usr/share
  - make uninstall PREFIX=/tmp/usr/local PREFIXSHARE=/tmp/usr/share
  - make clean
  - make dist
compiler:
  - clang
  - gcc
