--- !ditz.rubyforge.org,2008-03-06/project 
name: dwm-mitch
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: dwm-mitch
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "3.5"
  status: :released
  release_time: 2008-12-06 09:15:35.419656 Z
  log_events: 
  - - 2008-12-03 20:22:00.637799 Z
    - Christian Garbs <mitch@cgarbs.de>
    - created
    - ""
  - - 2008-12-06 09:15:35.419689 Z
    - Christian Garbs <mitch@cgarbs.de>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "3.6"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-12-06 09:18:52.062448 Z
    - Christian Garbs <mitch@cgarbs.de>
    - created
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 3.5.1
  status: :released
  release_time: 2009-03-03 21:42:12.554970 Z
  log_events: 
  - - 2008-12-27 22:49:12.790462 Z
    - Christian Garbs <mitch@cgarbs.de>
    - created
    - ship latest bugfix
  - - 2009-03-03 21:42:12.555004 Z
    - Christian Garbs <mitch@cgarbs.de>
    - released
    - subsequently document 3.5.1 release (2008-12-27)
